version: '2'
services:
    my_app:
      build: ./
      ports:
        - "7000:8080"
      depends_on:
        - my_mongodb
        - my_redis

      command: dockerize -wait tcp://my_mongodb:27017 -wait tcp://my_redis:6379 -timeout 300s

    my_mongodb:
      image: mongo
      ports:
        - "27017:27017"


    my_redis:
      image: redis
      ports:
        - "6379:6379"


